# Introduction to the Moore-Penrose Pseudo-Inverse
The Moore-Penrose pseudo-inverse (often denoted as A+) is a generalization
of the inverse matrix. It allows us to find a "best-fit" solution to a
system of linear equations Ax = b, even when the matrix A is not square
or is singular (non-invertible).

For a system Ax = b, the pseudo-inverse solution is given by x = A+b.
This solution has specific properties:
1. If a unique solution exists, the pseudo-inverse finds it.
2. If the system is overdetermined (more equations than unknowns, A is tall),
   the pseudo-inverse finds the least-squares solution that minimizes ||Ax - b||^2.
3. If the system is underdetermined (fewer equations than unknowns, A is wide),
   the pseudo-inverse finds the solution with the minimum Euclidean norm (||x||^2)
   among all possible solutions.

In [1]:
import numpy as np

print("--- Solving Linear Equations using Moore-Penrose Pseudo-Inverse ---")
print("Using numpy.linalg.pinv for calculation.\n")


--- Solving Linear Equations using Moore-Penrose Pseudo-Inverse ---
Using numpy.linalg.pinv for calculation.



### Example 1: Well-determined system (square, invertible matrix)
In this case, the pseudo-inverse will behave like the regular inverse.

In [2]:

print("--- Example 1: Well-determined System (Unique Solution) ---")
A1 = np.array([[2, 1],
               [1, 3]])
b1 = np.array([4, 7])

print("Matrix A1:\n", A1)
print("Vector b1:\n", b1)

# Calculate the pseudo-inverse of A1
A1_plus = np.linalg.pinv(A1)
print("Pseudo-inverse of A1:\n", A1_plus)

# Solve for x1
x1 = A1_plus @ b1
print("Solution x1 (A1+ @ b1):\n", x1)
print("Verification (A1 @ x1):\n", A1 @ x1)
print("-" * 50 + "\n")


--- Example 1: Well-determined System (Unique Solution) ---
Matrix A1:
 [[2 1]
 [1 3]]
Vector b1:
 [4 7]
Pseudo-inverse of A1:
 [[ 0.6 -0.2]
 [-0.2  0.4]]
Solution x1 (A1+ @ b1):
 [1. 2.]
Verification (A1 @ x1):
 [4. 7.]
--------------------------------------------------



### Example 2: Overdetermined system (more equations than unknowns)
No exact solution exists, so the pseudo-inverse finds the least-squares solution.


In [4]:
print("--- Example 2: Overdetermined System (Least-Squares Solution) ---")
A2 = np.array([[1, 1],
               [2, 1],
               [3, 1]])
b2 = np.array([2, 3, 5]) # This system is inconsistent

print("Matrix A2:\n", A2)
print("Vector b2:\n", b2)

# Calculate the pseudo-inverse of A2
A2_plus = np.linalg.pinv(A2)
print("Pseudo-inverse of A2:\n", A2_plus)

# Solve for x2 (least-squares solution)
x2 = A2_plus @ b2
print("Solution x2 (A2+ @ b2 - Least-Squares):\n", x2)
print("Verification (A2 @ x2) - Note the error:\n", A2 @ x2)
print("Residual (||A2 @ x2 - b2||):\n", np.linalg.norm(A2 @ x2 - b2))
print("-" * 50 + "\n")


--- Example 2: Overdetermined System (Least-Squares Solution) ---
Matrix A2:
 [[1 1]
 [2 1]
 [3 1]]
Vector b2:
 [2 3 5]
Pseudo-inverse of A2:
 [[-5.00000000e-01 -1.27409951e-16  5.00000000e-01]
 [ 1.33333333e+00  3.33333333e-01 -6.66666667e-01]]
Solution x2 (A2+ @ b2 - Least-Squares):
 [1.5        0.33333333]
Verification (A2 @ x2) - Note the error:
 [1.83333333 3.33333333 4.83333333]
Residual (||A2 @ x2 - b2||):
 0.408248290463863
--------------------------------------------------



### Example 3: Underdetermined system (fewer equations than unknowns)
Many solutions exist, the pseudo-inverse finds the one with minimum norm.


In [5]:
print("--- Example 3: Underdetermined System (Minimum-Norm Solution) ---")
A3 = np.array([[1, 2, 3],
               [4, 5, 6]])
b3 = np.array([7, 8])

print("Matrix A3:\n", A3)
print("Vector b3:\n", b3)

# Calculate the pseudo-inverse of A3
A3_plus = np.linalg.pinv(A3)
print("Pseudo-inverse of A3:\n", A3_plus)

# Solve for x3 (minimum-norm solution)
x3 = A3_plus @ b3
print("Solution x3 (A3+ @ b3 - Minimum-Norm):\n", x3)
print("Verification (A3 @ x3):\n", A3 @ x3)
print("Norm of x3 (||x3||):\n", np.linalg.norm(x3))
print("-" * 50 + "\n")


--- Example 3: Underdetermined System (Minimum-Norm Solution) ---
Matrix A3:
 [[1 2 3]
 [4 5 6]]
Vector b3:
 [7 8]
Pseudo-inverse of A3:
 [[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]
Solution x3 (A3+ @ b3 - Minimum-Norm):
 [-3.05555556  0.11111111  3.27777778]
Verification (A3 @ x3):
 [7. 8.]
Norm of x3 (||x3||):
 4.482476167543181
--------------------------------------------------



### Example 4: Singular (non-invertible) square matrix
Even though it's square, it's singular, so a regular inverse doesn't exist.
Pseudo-inverse can still find a solution (least-squares if inconsistent,
minimum-norm if consistent with multiple solutions).


In [13]:
print("--- Example 4: Singular Square Matrix ---")
A4 = np.array([[1, 2],
               [2, 4]]) # This matrix is singular (rows are linearly dependent)
b4 = np.array([3, 6]) # This system is consistent (multiple solutions)

print("Matrix A4:\n", A4)
print("Vector b4:\n", b4)

# Calculate the pseudo-inverse of A4
A4_plus = np.linalg.pinv(A4)
print("Pseudo-inverse of A4:\n", A4_plus)

# Solve for x4
x4 = A4_plus @ b4
print("Solution x4 (A4+ @ b4 - Minimum-Norm):\n", x4)
print("Verification (A4 @ x4):\n", A4 @ x4)
print("Norm of x4 (||x4||):\n", np.linalg.norm(x4))
print("-" * 50 + "\n")

# --- How to interpret the results ---
# - For well-determined systems, x will be the exact unique solution.
# - For overdetermined systems, x will be the least-squares approximation.
#   The residual (||Ax - b||) will indicate how well the solution fits.
# - For underdetermined systems, x will be one of infinitely many solutions,
#   specifically the one with the smallest Euclidean norm.

--- Example 4: Singular Square Matrix ---
Matrix A4:
 [[1 2]
 [2 4]]
Vector b4:
 [3 6]
Pseudo-inverse of A4:
 [[0.04 0.08]
 [0.08 0.16]]
Solution x4 (A4+ @ b4 - Minimum-Norm):
 [0.6 1.2]
Verification (A4 @ x4):
 [3. 6.]
Norm of x4 (||x4||):
 1.3416407864998734
--------------------------------------------------

