### Example 1: Well-Determined System

In [1]:
import numpy as np

# --- Example 1: Well-Determined System (as before) ---
print("--- Example 1: Well-Determined System ---")
# Let's consider a 3x3 linear system:
# 2x + 3y - z = 1
# 4x - y + 2z = 8
# x + 2y + 5z = 10

A_well_determined = np.array([
    [2, 3, -1],
    [4, -1, 2],
    [1, 2, 5]
])
b_well_determined = np.array([1, 8, 10])

print("Coefficient Matrix (A_well_determined):\n", A_well_determined)
print("\nConstant Vector (b_well_determined):\n", b_well_determined)

try:
    det_A_well_determined = np.linalg.det(A_well_determined)
    print(f"\nDeterminant of A_well_determined: {det_A_well_determined:.4f}")
    if np.isclose(det_A_well_determined, 0):
        print("Warning: The determinant is close to zero. The matrix might be singular or ill-conditioned.")
    else:
        print("The matrix A_well_determined is non-singular, indicating a unique solution exists.")

    x_well_determined = np.linalg.solve(A_well_determined, b_well_determined)
    print("\nSolution Vector (x_well_determined):\n", x_well_determined)
    verification_well_determined = A_well_determined @ x_well_determined
    print("\nVerification (A_well_determined * x_well_determined):\n", verification_well_determined)
    print("Is A_well_determined * x_well_determined approximately equal to b_well_determined?", np.allclose(verification_well_determined, b_well_determined))

except np.linalg.LinAlgError as e:
    print(f"\nError: Could not solve the system for A_well_determined. {e}")
    print("This usually means the coefficient matrix is singular (determinant is zero).")
except Exception as e:
    print(f"\nAn unexpected error occurred for A_well_determined: {e}")


--- Example 1: Well-Determined System ---
Coefficient Matrix (A_well_determined):
 [[ 2  3 -1]
 [ 4 -1  2]
 [ 1  2  5]]

Constant Vector (b_well_determined):
 [ 1  8 10]

Determinant of A_well_determined: -81.0000
The matrix A_well_determined is non-singular, indicating a unique solution exists.

Solution Vector (x_well_determined):
 [1.17283951 0.12345679 1.71604938]

Verification (A_well_determined * x_well_determined):
 [ 1.  8. 10.]
Is A_well_determined * x_well_determined approximately equal to b_well_determined? True


### Example 2: Singular Matrix

In [2]:
print("\n\n--- Example 2: Singular Matrix ---")
# Consider a system where one row is a linear combination of others.
# This makes the matrix singular and the system either has no solution or infinite solutions.
# Example:
# x + y = 2
# 2x + 2y = 4  (This is just 2 times the first equation)
# x - y = 0

A_singular = np.array([
    [1, 1],
    [2, 2]
])
b_singular_consistent = np.array([2, 4]) # Consistent system (infinite solutions)
b_singular_inconsistent = np.array([2, 5]) # Inconsistent system (no solutions)

print("Coefficient Matrix (A_singular):\n", A_singular)
print("\nConstant Vector (b_singular_consistent):\n", b_singular_consistent)
print("Constant Vector (b_singular_inconsistent):\n", b_singular_inconsistent)

try:
    det_A_singular = np.linalg.det(A_singular)
    print(f"\nDeterminant of A_singular: {det_A_singular:.4f}")

    if np.isclose(det_A_singular, 0):
        print("The determinant is zero. The matrix A_singular is singular.")
        print("This system does not have a unique solution.")
    else:
        print("The matrix A_singular is non-singular, indicating a unique solution exists.")

    # Attempt to solve with the consistent singular system
    print("\nAttempting to solve A_singular * x = b_singular_consistent:")
    x_singular_consistent = np.linalg.solve(A_singular, b_singular_consistent)
    print("Solution Vector (x_singular_consistent):\n", x_singular_consistent) # This line will not be reached

except np.linalg.LinAlgError as e:
    print(f"\nCaught LinAlgError for A_singular * x = b_singular_consistent: {e}")
    print("As expected, numpy.linalg.solve raises an error for a singular matrix.")
except Exception as e:
    print(f"\nAn unexpected error occurred for A_singular * x = b_singular_consistent: {e}")

print("\nAttempting to solve A_singular * x = b_singular_inconsistent:")
try:
    # Attempt to solve with the inconsistent singular system
    x_singular_inconsistent = np.linalg.solve(A_singular, b_singular_inconsistent)
    print("Solution Vector (x_singular_inconsistent):\n", x_singular_inconsistent) # This line will not be reached

except np.linalg.LinAlgError as e:
    print(f"\nCaught LinAlgError for A_singular * x = b_singular_inconsistent: {e}")
    print("As expected, numpy.linalg.solve raises an error for a singular matrix, regardless of consistency.")
except Exception as e:
    print(f"\nAn unexpected error occurred for A_singular * x = b_singular_inconsistent: {e}")




--- Example 2: Singular Matrix ---
Coefficient Matrix (A_singular):
 [[1 1]
 [2 2]]

Constant Vector (b_singular_consistent):
 [2 4]
Constant Vector (b_singular_inconsistent):
 [2 5]

Determinant of A_singular: 0.0000
The determinant is zero. The matrix A_singular is singular.
This system does not have a unique solution.

Attempting to solve A_singular * x = b_singular_consistent:

Caught LinAlgError for A_singular * x = b_singular_consistent: Singular matrix
As expected, numpy.linalg.solve raises an error for a singular matrix.

Attempting to solve A_singular * x = b_singular_inconsistent:

Caught LinAlgError for A_singular * x = b_singular_inconsistent: Singular matrix
As expected, numpy.linalg.solve raises an error for a singular matrix, regardless of consistency.


### Underdetermined System

In [7]:
# --- Example 3: Underdetermined System ---
print("\n\n--- Example 3: Underdetermined System ---")
# An underdetermined system has fewer equations than unknowns (m < n).
# If consistent, it has infinitely many solutions.
# numpy.linalg.solve is not suitable here; use numpy.linalg.lstsq to find
# the least-squares solution, which is the solution with the minimum Euclidean norm.

# Example:
# x + 2y + 3z = 6
# 4x + 5y + 6z = 15

A_underdetermined = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
b_underdetermined = np.array([6, 15])

print("Coefficient Matrix (A_underdetermined):\n", A_underdetermined)
print("\nConstant Vector (b_underdetermined):\n", b_underdetermined)

try:
    # For underdetermined systems, np.linalg.lstsq is used to find the
    # least-squares solution. It returns a tuple:
    # - x: The least-squares solution.
    # - residuals: Sum of squared residuals.
    # - rank: Rank of the matrix A.
    # - s: Singular values of A.
    x_underdetermined, residuals, rank, s = np.linalg.lstsq(A_underdetermined, b_underdetermined, rcond=None)

    print("\nLeast-squares Solution Vector (x_underdetermined):\n", x_underdetermined)
    print(f"Rank of A_underdetermined: {rank}")
    print(f"Residuals: {residuals}") # Empty if exact solution exists and is found

    # Verification: A @ x should approximate b
    verification_underdetermined = A_underdetermined @ x_underdetermined
    print("\nVerification (A_underdetermined * x_underdetermined):\n", verification_underdetermined)
    print("Is A_underdetermined * x_underdetermined approximately equal to b_underdetermined?", np.allclose(verification_underdetermined, b_underdetermined))

except Exception as e:
    print(f"\nAn error occurred while solving the underdetermined system: {e}")





--- Example 3: Underdetermined System ---
Coefficient Matrix (A_underdetermined):
 [[1 2 3]
 [4 5 6]]

Constant Vector (b_underdetermined):
 [ 6 15]

Least-squares Solution Vector (x_underdetermined):
 [1. 1. 1.]
Rank of A_underdetermined: 2
Residuals: []

Verification (A_underdetermined * x_underdetermined):
 [ 6. 15.]
Is A_underdetermined * x_underdetermined approximately equal to b_underdetermined? True


In [10]:
# --- Example 3: Underdetermined System ---
import numpy as np
from scipy.linalg import null_space

# Define the coefficient matrix A and the constant vector b
A = np.array([[1, 2, -1],
              [3, -1, 2]])

b = np.array([5, 1])

print("Matrix A:\n", A)
print("\nVector b:\n", b)

# --- Step 1: Check for consistency (optional, but good practice) ---
# For an underdetermined system, if solutions exist, they are infinite.
# The rank of A must be equal to the rank of the augmented matrix [A|b]
# for a solution to exist.
rank_A = np.linalg.matrix_rank(A)
augmented_A = np.hstack((A, b.reshape(-1, 1))) # Create augmented matrix
rank_augmented_A = np.linalg.matrix_rank(augmented_A)

print(f"\nRank of A: {rank_A}")
print(f"Rank of augmented A: {rank_augmented_A}")

if rank_A != rank_augmented_A:
    print("\nNo solution exists for this system.")
else:
    print("\nSolutions exist for this system (potentially infinite).")

    # --- Solution Method 1: Using np.linalg.pinv (Pseudoinverse) ---
    # The pseudoinverse (Moore-Penrose inverse) gives the minimum-norm solution.
    print("\n--- Solving using np.linalg.pinv (Pseudoinverse) ---")
    A_pinv = np.linalg.pinv(A)
    x_particular_pinv = A_pinv @ b

    print("\nPseudoinverse of A:\n", A_pinv)
    print("\nParticular solution (minimum-norm) from pinv:\n", x_particular_pinv)

    # Verify the particular solution
    print("\nVerification (A @ x_particular_pinv):\n", A @ x_particular_pinv)

    # --- Finding the null space of A (applicable to both methods for general solution) ---
    # The null space contains all vectors x_n such that A @ x_n = 0.
    # Any linear combination of these basis vectors can be added to the particular solution.
    # scipy.linalg.null_space returns an orthonormal basis for the null space.
    null_space_basis = null_space(A)

    print("\nBasis for the null space of A:\n", null_space_basis)

    # --- Construct the general solution ---
    # The general solution is x = x_particular + c1*v1 + c2*v2 + ...
    # where v1, v2, ... are the basis vectors of the null space, and c1, c2, ... are arbitrary scalars.

    print("\nGeneral Solution Form (using pinv's particular solution):")
    print("x = x_particular_pinv + c * null_space_basis_vector")
    # Assuming one basis vector for simplicity, adjust if null_space_basis has more columns
    if null_space_basis.shape[1] > 0:
        print(f"x = {x_particular_pinv} + c * {null_space_basis[:, 0]}")
    else:
        print("Null space is trivial (only the zero vector).")


    # Example: Let's pick an arbitrary scalar 'c' (e.g., c = 10)
    if null_space_basis.shape[1] > 0:
        c = 10
        another_solution = x_particular_pinv + c * null_space_basis[:, 0]
        print(f"\nExample solution with c = {c}:\n", another_solution)

        # Verify this new solution
        print("\nVerification (A @ another_solution):\n", A @ another_solution)

        # Example: Let's pick an arbitrary scalar 'c' (e.g., c = -5)
        c = -5
        yet_another_solution = x_particular_pinv + c * null_space_basis[:, 0]
        print(f"\nExample solution with c = {c}:\n", yet_another_solution)

        # Verify this new solution
        print("\nVerification (A @ yet_another_solution):\n", A @ yet_another_solution)


    # --- Solution Method 2: Using np.linalg.lstsq ---
    # For underdetermined systems, lstsq returns the minimum-norm solution.
    print("\n--- Solving using np.linalg.lstsq ---")
    x_lstsq, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)

    print("\nSolution from np.linalg.lstsq (minimum-norm):\n", x_lstsq)
    print("Residuals (should be close to zero for consistent systems):\n", residuals)
    print("Rank of A from lstsq:\n", rank)
    print("Singular values of A:\n", s)

    # Verify the lstsq solution
    print("\nVerification (A @ x_lstsq):\n", A @ x_lstsq)

    # Note: x_particular_pinv and x_lstsq should be identical for consistent underdetermined systems.
    print("\nComparison of solutions:")
    print(f"Solution from pinv: {x_particular_pinv}")
    print(f"Solution from lstsq: {x_lstsq}")
    print(f"Are they close? {np.allclose(x_particular_pinv, x_lstsq)}")


Matrix A:
 [[ 1  2 -1]
 [ 3 -1  2]]

Vector b:
 [5 1]

Rank of A: 2
Rank of augmented A: 2

Solutions exist for this system (potentially infinite).

--- Solving using np.linalg.pinv (Pseudoinverse) ---

Pseudoinverse of A:
 [[ 0.20481928  0.22891566]
 [ 0.3253012  -0.04819277]
 [-0.14457831  0.13253012]]

Particular solution (minimum-norm) from pinv:
 [ 1.25301205  1.57831325 -0.59036145]

Verification (A @ x_particular_pinv):
 [5. 1.]

Basis for the null space of A:
 [[-0.32929278]
 [ 0.5488213 ]
 [ 0.76834982]]

General Solution Form (using pinv's particular solution):
x = x_particular_pinv + c * null_space_basis_vector
x = [ 1.25301205  1.57831325 -0.59036145] + c * [-0.32929278  0.5488213   0.76834982]

Example solution with c = 10:
 [-2.03991575  7.06652625  7.09313675]

Verification (A @ another_solution):
 [5. 1.]

Example solution with c = -5:
 [ 2.89947595 -1.16579325 -4.43211055]

Verification (A @ yet_another_solution):
 [5. 1.]

--- Solving using np.linalg.lstsq ---

Soluti

In [ ]:
# --- Example 4: Underdetermined System ---
print("\n\n--- Example 4: Underdetermined System ---")
# An underdetermined system has fewer equations than unknowns (m < n).
# If consistent, it has infinitely many solutions.
# numpy.linalg.solve is not suitable here; use numpy.linalg.lstsq to find
# the least-squares solution, which is the solution with the minimum Euclidean norm.

# Example:
# x + 2y - z = 5
# 3x - y + 2z = 1

A_underdetermined = np.array([
    [1, 2, -1],
    [3, -1, 2]
])
b_underdetermined = np.array([5, 1])

print("Coefficient Matrix (A_underdetermined):\n", A_underdetermined)
print("\nConstant Vector (b_underdetermined):\n", b_underdetermined)

try:
    # For underdetermined systems, np.linalg.lstsq is used to find the
    # least-squares solution. It returns a tuple:
    # - x: The least-squares solution.
    # - residuals: Sum of squared residuals.
    # - rank: Rank of the matrix A.
    # - s: Singular values of A.
    x_underdetermined, residuals, rank, s = np.linalg.lstsq(A_underdetermined, b_underdetermined, rcond=None)

    print("\nLeast-squares Solution Vector (x_underdetermined):\n", x_underdetermined)
    print(f"Rank of A_underdetermined: {rank}")
    print(f"Residuals: {residuals}") # Empty if exact solution exists and is found

    # Verification: A @ x should approximate b
    verification_underdetermined = A_underdetermined @ x_underdetermined
    print("\nVerification (A_underdetermined * x_underdetermined):\n", verification_underdetermined)
    print("Is A_underdetermined * x_underdetermined approximately equal to b_underdetermined?", np.allclose(verification_underdetermined, b_underdetermined))

except Exception as e:
    print(f"\nAn error occurred while solving the underdetermined system: {e}")




--- Example 3: Underdetermined System ---
Coefficient Matrix (A_underdetermined):
 [[ 1  2 -1]
 [ 3 -1  2]]

Constant Vector (b_underdetermined):
 [5 1]

Least-squares Solution Vector (x_underdetermined):
 [ 1.25301205  1.57831325 -0.59036145]
Rank of A_underdetermined: 2
Residuals: []

Verification (A_underdetermined * x_underdetermined):
 [5. 1.]
Is A_underdetermined * x_underdetermined approximately equal to b_underdetermined? True


## Overdetermined System of Linear Equations
An overdetermined system has more equations than variables (m > n).
Such systems generally do not have an exact solution that satisfies all equations.
Instead, we look for a 'least squares' solution that minimizes the sum of the squares of the residuals.
This means finding the x that minimizes ||Ax - b||<sup>2</sup> where
`numpy.linalg.lstsq` is the primary function used for this purpose.

In [13]:
import numpy as np

# Define an example overdetermined system:
# x + y = 2
# 2x - y = 1
# x + 2y = 4
A_over = np.array([[1, 1],
                   [2, -1],
                   [1, 2]])

b_over = np.array([2, 1, 4])

print("\nMatrix A (Overdetermined):\n", A_over)
print("\nVector b (Overdetermined):\n", b_over)

# --- Solving Overdetermined System using np.linalg.lstsq ---
# For overdetermined systems, lstsq finds the least-squares solution.
print("\n--- Solving Overdetermined System using np.linalg.lstsq ---")
x_lstsq_over, residuals_over, rank_over, s_over = np.linalg.lstsq(A_over, b_over, rcond=None)

print("\nLeast-squares solution from np.linalg.lstsq (Overdetermined):\n", x_lstsq_over)
print("Residuals (sum of squared residuals):", residuals_over)
print("Rank of A_over from lstsq:\n", rank_over)
print("Singular values of A_over:\n", s_over)

# Verify the solution (A @ x should be close to b, but not necessarily equal)
print("\nVerification (A_over @ x_lstsq_over):\n", A_over @ x_lstsq_over)
print("\nOriginal b_over:\n", b_over)
print("\nDifference (A_over @ x_lstsq_over - b_over):\n", A_over @ x_lstsq_over - b_over)

# The residuals array returned by lstsq is the sum of squared residuals,
# or an empty array if rank(A) < n or if b is 1-D.
# To get individual residuals:
individual_residuals_over = A_over @ x_lstsq_over - b_over
print("\nIndividual residuals (A_over @ x - b_over):\n", individual_residuals_over)
print("Sum of squared individual residuals:", np.sum(individual_residuals_over**2))



Matrix A (Overdetermined):
 [[ 1  1]
 [ 2 -1]
 [ 1  2]]

Vector b (Overdetermined):
 [2 1 4]

--- Solving Overdetermined System using np.linalg.lstsq ---

Least-squares solution from np.linalg.lstsq (Overdetermined):
 [1.11428571 1.31428571]
Residuals (sum of squared residuals): [0.25714286]
Rank of A_over from lstsq:
 2
Singular values of A_over:
 [2.64575131 2.23606798]

Verification (A_over @ x_lstsq_over):
 [2.42857143 0.91428571 3.74285714]

Original b_over:
 [2 1 4]

Difference (A_over @ x_lstsq_over - b_over):
 [ 0.42857143 -0.08571429 -0.25714286]

Individual residuals (A_over @ x - b_over):
 [ 0.42857143 -0.08571429 -0.25714286]
Sum of squared individual residuals: 0.25714285714285734
