# NumPy Examples

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.</br>
The following example code introduces some of the features on NumPy.  See the NumPy documentation for more information.</br>
[NumPy documentation](https://numpy.org/doc/stable/index.html)

In [32]:
import numpy as np

# Create a 1D array (vector)
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

# Create a 2D array (matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

# Create a 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", arr_3d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


NumPy also provides functions to create arrays with initial placeholder content:

In [33]:
# Array of zeros
zeros_arr = np.zeros((3, 4)) # 3 rows, 4 columns
print("Array of Zeros:\n", zeros_arr)

# Array of ones
ones_arr = np.ones((2, 2))
print("Array of Ones:\n", ones_arr)

# Empty array (values are uninitialized, whatever is in memory)
empty_arr = np.empty((2, 3))
print("Empty Array:\n", empty_arr)

# Array with a range of values
range_arr = np.arange(0, 10, 2) # Start, Stop (exclusive), Step
print("Range Array:", range_arr)

# Linearly spaced array
linspace_arr = np.linspace(0, 10, 5) # Start, Stop (inclusive), Number of elements
print("Linspace Array:", linspace_arr)


Array of Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array of Ones:
 [[1. 1.]
 [1. 1.]]
Empty Array:
 [[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]
Range Array: [0 2 4 6 8]
Linspace Array: [ 0.   2.5  5.   7.5 10. ]


### Array Attributes
* .ndim: The number of dimensions (axes) of the array.

* .shape: A tuple indicating the size of the array in each dimension.

* .size: The total number of elements in the array.

* .dtype: The data type of the elements in the array.

In [34]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

Dimensions: 2
Shape: (2, 3)
Size: 6
Data Type: int64


### Element-wise Operations
Arithmetic operations (+, -, *, /) are performed element-wise.

In [35]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Addition:", arr1 + arr2)
print("Multiplication:", arr1 * arr2)

Addition: [5 7 9]
Multiplication: [ 4 10 18]


### Broadcasting
Broadcasting is a powerful mechanism that allows NumPy to perform operations on arrays of different shapes. It implicitly "stretches" the smaller array to match the larger one, provided they are compatible.



In [36]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10

print("Array + Scalar:\n", arr + scalar) # Scalar is broadcast to all elements
print("Array - Scalar:\n", arr - scalar)
print("Array * Scalar:\n", arr * scalar)
print("Array / Scalar:\n", arr / scalar)

Array + Scalar:
 [[11 12 13]
 [14 15 16]]
Array - Scalar:
 [[-9 -8 -7]
 [-6 -5 -4]]
Array * Scalar:
 [[10 20 30]
 [40 50 60]]
Array / Scalar:
 [[0.1 0.2 0.3]
 [0.4 0.5 0.6]]


### Universal Functions (ufuncs) 
NumPy provides many universal functions (ufuncs) that operate element-wise on arrays, such as np.sqrt(), np.sin(), np.cos(), np.exp(), etc.

In [37]:
arr = np.array([1, 4, 9])
print("Square Root:", np.sqrt(arr))
print("Sine:", np.sin(arr))
print("Cosine:", np.cos(arr))
print("Exponential:", np.exp(arr))

Square Root: [1. 2. 3.]
Sine: [ 0.84147098 -0.7568025   0.41211849]
Cosine: [ 0.54030231 -0.65364362 -0.91113026]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03]


### Aggregate Functions
NumPy offers functions to perform aggregations (e.g., sum, mean, min, max) along specified axes.

In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum of all elements:", np.sum(arr))
print("Sum along columns (axis=0):", np.sum(arr, axis=0)) # Sum of [1,4], [2,5], [3,6]
print("Sum along rows (axis=1):", np.sum(arr, axis=1))    # Sum of [1,2,3], [4,5,6]

print("Mean of all elements:", np.mean(arr))
print("Maximum element:", np.max(arr))

Sum of all elements: 21
Sum along columns (axis=0): [5 7 9]
Sum along rows (axis=1): [ 6 15]
Mean of all elements: 3.5
Maximum element: 6


## Indexing and Slicing
### Basic Indexing 


In [39]:
arr = np.array([10, 20, 30, 40, 50])

print("First element:", arr[0])
print("Last element:", arr[-1])

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Element at (0, 1):", matrix[0, 1]) # Row 0, Column 1 (value 2)
print("Element at (2, 0):", matrix[2, 0]) # Row 2, Column 0 (value 7)


First element: 10
Last element: 50
Element at (0, 1): 2
Element at (2, 0): 7


### Slicing
Slicing allows you to extract subarrays. The syntax is start:stop:step

In [40]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print("Elements from index 2 to 5:", arr[2:6])    # [2 3 4 5]
print("Elements from beginning to index 4:", arr[:5]) # [0 1 2 3 4]
print("Elements from index 5 to end:", arr[5:])    # [5 6 7 8 9]
print("Every other element:", arr[::2])         # [0 2 4 6 8]
print("Reversed array:", arr[::-1])           # [9 8 7 6 5 4 3 2 1 0]

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("First two rows:\n", matrix[:2, :])
print("All rows, last column:\n", matrix[:, 2])
print("Sub-matrix (rows 0-1, cols 1-2):\n", matrix[0:2, 1:3])


Elements from index 2 to 5: [2 3 4 5]
Elements from beginning to index 4: [0 1 2 3 4]
Elements from index 5 to end: [5 6 7 8 9]
Every other element: [0 2 4 6 8]
Reversed array: [9 8 7 6 5 4 3 2 1 0]
First two rows:
 [[1 2 3]
 [4 5 6]]
All rows, last column:
 [3 6 9]
Sub-matrix (rows 0-1, cols 1-2):
 [[2 3]
 [5 6]]


### Reshaping Arrays 
Changing the shape of an array without changing its data is a common operation.

    reshape()

The reshape() method returns a new array with the specified shape.

In [41]:
arr = np.arange(12) # [ 0  1  2  3  4  5  6  7  8  9 10 11]
print("Original Array:", arr)

# Reshape to a 3x4 matrix
reshaped_arr = arr.reshape(3, 4)
print("Reshaped to 3x4:\n", reshaped_arr)

# Reshape to a 2x2x3 3D array
reshaped_3d = arr.reshape(2, 2, 3)
print("Reshaped to 2x2x3:\n", reshaped_3d)

# Use -1 for an unknown dimension (NumPy calculates it)
reshaped_auto = arr.reshape(4, -1) # 4 rows, NumPy calculates columns
print("Reshaped with auto-dimension:\n", reshaped_auto)

# Transpose a 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Matrix:\n", matrix)
print("Matrix Transpose:\n", matrix.T)

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x2x3:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Reshaped with auto-dimension:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


## Linear Algebra with NumPy
NumPy provides capabilities for several linear algebra operations; however, it is recommended to use scipy.linalg for a more robust linear algebra operations.

### Dot Product 
The dot product of two arrays (vectors or  2-D matrices) can be calculated using np.dot(), np.matmul, or the @ operator (for matrix multiplication). However, for n-dimensional arrays, they work differently.

In [42]:
# Vector dot product
vec1 = np.array([1, 2])
vec2 = np.array([3, 4])
dot_product = np.dot(vec1, vec2)
print("Vector Dot Product:", dot_product) # (1*3) + (2*4) = 11

# Matrix multiplication
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(mat1, mat2)
# or using the @ operator to achieve the same result
matrix_product_at = mat1 @ mat2
print("Matrix Product (np.dot):\n", matrix_product)
print("Matrix Product (@ operator):\n", matrix_product_at)


Vector Dot Product: 11
Matrix Product (np.dot):
 [[19 22]
 [43 50]]
Matrix Product (@ operator):
 [[19 22]
 [43 50]]


### Determinant, Inverse, Eigenvalues
NumPy's linalg module provides functions for advanced linear algebra.



In [43]:
from numpy import linalg

matrix = np.array([[1, 2], [3, 4]])

# Determinant
det = linalg.det(matrix)
print(f"Determinant: {det:.2f}")

# Inverse
inv_matrix = linalg.inv(matrix)
print(f"Inverse Matrix:\n {inv_matrix}")

# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = linalg.eig(matrix)
print(f"Eigenvalues: {np.array2string(eigenvalues, formatter={'float': lambda x: f'{x:.2f}'})}")
print(f"Eigenvectors:\n {np.array2string(eigenvectors, formatter={'float': lambda x: f'{x:.2f}'})}")

Determinant: -2.00
Inverse Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37 5.37]
Eigenvectors:
 [[-0.82 -0.42]
 [0.57 -0.91]]


### Solve linear matrix equation with M equations and M unknows </br>

    x = numpy.linalg.solve(A,b)
    where A: (M,M) array of scalars
          b: (M,K) array of scalars
          x: (M,K) array of scalars
    LinAlgError occurs is a is not square or is singular

Solve the system of equations
$$ A x = b \\
x_0 + 2 x_1 = 1 \\
3 x_0 + 5 x_1 = 2
$$

In [2]:
import numpy as np

a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
x = np.linalg.solve(a, b)
print("Solution to Ax = b:\n", x)

Solution to Ax = b:
 [-1.  1.]


**Note**: A and A inverse are a 2x2 arrays and b is a 1x2 row vector. b is treated as a column vector in the solution $x = A^{-1} b$, and presented as a row vector.